### ISSUE TITLE
Autograder timeout issue

### ISSUE THREAD

**Issue by hmumixaM** [comp426-2022-spring/a01#7]
I believe that my code work correctly, but the autograder keep sending me timeout result.

**Comment by WidAlsa0** [comment]
I have also had the same issue and cancelled the workflow as a result. Any tips would be helpful.

**Comment by sningle** [comment]
I had the same issue. I've noticed if I use browser-sync that it works correctly if I use "localhost:3000/www" but that doesn't seem to translate in the autograder.

**Comment by samrshi** [comment]
#5 says that the autograder is not yet fully configured and that there should be an announcement when it's completed. That might be related.

**Comment by jdmar3** [comment]
A few points to consider:

1. The autograder is not fully configured and if you look at the output it includes a message saying that it is still being tested. The autograder is not magic. It's just a bunch of scripty input/output tests that match things in STDOUT based on what your scripts DO in response to being run in certain ways and in certain contexts. Right now, I'm testing to make sure that I can check for a random port assignment. Once that succeeds, then it will be fully configured.
2. The timeouts occur sometimes because runners aren't available. It's okay. Just leave them. Eventually a runner will come available and then you will be able to see the results on GitHub. It doesn't happen instantly. Each time you push, it is submitted as a job in a queue.
3. You should not be using browser-sync for a01. You are writing a server script that does what browser-sync does. Of course if you use browser-sync to test this it will seem like it works because browser-sync works. If browser-sync works to serve the html file at ./www/index.html but your script does not, then that means that your script doesn't work.

I will go over this in class today in greater detail, because I think it would benefit everyone to understand how the autograder works so that you are not using it as your only method for testing your work. Also, we can go over ways to operationalize the assignment instructions into tests that you can do to identify issues in your code.

**Comment by jdmar3** [comment]
As of about 11:30 this morning, the a001 autograder is up and running and fully configured.
